<?php
/**
 * Medma Marketplace
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Magento Team
 * that is bundled with this package of Medma Infomatix Pvt. Ltd.
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Contact us Support does not guarantee correct work of this package
 * on any other Magento edition except Magento COMMUNITY edition.
 * =================================================================
 * 
 * @category    Medma
 * @package     Medma_MarketPlace
**/
?>
<?php $_item = $this->getItem() ?>
<tr class="border" id="order-item-row-<?php echo $_item->getId() ?>">
    <td><h3 class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></h3>
        <?php if($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <?php if (!$this->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                    <?php echo $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="truncated_full_value">
                        <dl class="item-options">
                            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                            <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd>
                    <?php echo nl2br($this->escapeHtml( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) )) ?>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $this->escapeHtml($_item->getDescription()) ?>
        <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
            <a href="#" id="order-item-gift-message-link-<?php echo $_item->getId() ?>" class="gift-message-link" onclick="return giftMessageToogle('<?php echo $_item->getId() ?>')"><?php echo $this->__('Gift Message') ?></a>
        <?php endif; ?>
    </td>
    <td><?php echo $this->escapeHtml(Mage::helper('core/string')->splitInjection($this->getSku())) ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price">
                    <?php endif; ?>
                        <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice() + $this->getItem()->getWeeeTaxAppliedAmount() + $this->getItem()->getWeeeTaxDisposition()); ?>
                    <?php else: ?>
                        <?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?>
                    <?php endif; ?>

                </span>


                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="eunit-item-tax-details<?php echo $this->getItem()->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['amount']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['amount']); ?></small></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['amount']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php endif; ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()+$this->getItem()->getWeeeTaxAppliedAmount()+$this->getItem()->getWeeeTaxDisposition()); ?></span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br />
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                   <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price">
                    <?php endif; ?>
                        <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($this->getItem()); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                    <?php else: ?>
                        <?php echo $this->getOrder()->formatPrice($_incl-$this->getItem()->getWeeeTaxDisposition()) ?>
                    <?php endif; ?>

                </span>


                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="unit-item-tax-details<?php echo $this->getItem()->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['amount_incl_tax']); ?></small></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php endif; ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </td>
    <td class="a-right">
        <span class="nobr">
                <?php if ($this->getItem()->getQtyOrdered() > 0): ?>
            <?php echo $this->__('Ordered'); ?>: <strong><?php echo $this->getItem()->getQtyOrdered()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyShipped() > 0): ?>
            <?php echo $this->__('Shipped'); ?>: <strong><?php echo $this->getItem()->getQtyShipped()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyCanceled() > 0): ?>
            <?php echo $this->__('Canceled'); ?>: <strong><?php echo $this->getItem()->getQtyCanceled()*1 ?></strong><br />
        <?php endif; ?>
        <?php if ($this->getItem()->getQtyRefunded() > 0): ?>
            <?php echo $this->__('Refunded'); ?>: <strong><?php echo $this->getItem()->getQtyRefunded()*1 ?></strong><br />
        <?php endif; ?>
        </span>
    </td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price">
                    <?php endif; ?>
                        <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                <?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()+$this->getItem()->getWeeeTaxAppliedRowAmount()+$this->getItem()->getWeeeTaxRowDisposition()); ?>
                    <?php else: ?>
                        <?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?>
                    <?php endif; ?>

                </span>


                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['row_amount']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['row_amount']); ?></small></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['row_amount']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php endif; ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()+$this->getItem()->getWeeeTaxAppliedRowAmount()+$this->getItem()->getWeeeTaxRowDisposition()); ?></span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </span>
            <br />
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                   <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-price">
                    <?php endif; ?>
                        <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                    <?php if (!Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($this->getItem()); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                    <?php else: ?>
                        <?php echo $this->getOrder()->formatPrice($_incl-$this->getItem()->getWeeeTaxRowDisposition()) ?>
                    <?php endif; ?>

                </span>


                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>

                    <span class="cart-tax-info" id="subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></small></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                            </small>
                        <?php endif; ?>
                    </span>

                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>



            </span>
        <?php endif; ?>
    </td>
    <!--
    <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
    <th class="a-right"><?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?></th>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
    <th class="a-right"><?php echo $this->getOrder()->formatPrice($this->helper('checkout')->getSubtotalInclTax($this->getItem())); ?></th>
    <?php endif; ?>
    -->
    
    <td class="a-right">
        <a href="javascript: void(0);" onclick="showFeedbackForm(this, <?php echo $_item->getId() ?>);"><?php echo $this->__('Feedback'); ?></a>
    </td>
</tr>

<?php $vendorProfile = $this->getVendorProfile(); ?>
<?php $invoiceItemId = $this->getInvoiceItemId(); ?>
<tr class="feedback-row border" id="order-item-row-feedback-<?php echo $_item->getId() ?>">
    <td colspan="6">		
		<div class="feedback-collateral">			
			<?php if($invoiceItemId > 0): ?>
				<?php if(!is_null($vendorProfile->getId())): ?>
					<form method="post" id="<?php echo $this->getFormId($invoiceItemId); ?>" action="<?php echo $this->getRatingSaveUrl($invoiceItemId, $_item->getOrderId()); ?>">			
						<h2><?php echo $this->__('Write Your Own Review'); ?></h2>
						<p><?php echo $this->__('You\'re reviewing: '); ?><a href="<?php echo $this->getVendorProfileUrl($vendorProfile->getId()); ?>"><b><?php echo $vendorProfile->getShopName(); ?></b></a></p>
						<p><b><?php echo $this->__('How do you rate this product? *'); ?></b></p>
						<?php echo $this->getLayout()->createBlock('marketplace/vendor_ratings')->setData('invoice_item_id', $invoiceItemId)->toHtml(); ?>
						<?php echo $this->getLayout()->createBlock('marketplace/vendor_reviews')->setData('invoice_item_id', $invoiceItemId)->toHtml(); ?>
						<div class="feedback-buttons-set">
							<button type="submit" title="<?php echo $this->__('Submit Review'); ?>" class="button">
								<span><span><?php echo $this->__('Submit Review'); ?></span></span>
							</button>
						</div>
					</form>
					<script type="text/javascript">
						//<![CDATA[
						var reviewForm= new VarienForm('<?php echo $this->getFormId($invoiceItemId); ?>', true);
						//]]>
					</script>
				<?php else: ?>
					<p><?php echo '<b>' . $this->__('NOTE: ') . '</b>' . $this->__('This item uploaded by site admin. you can give feed back to vendor only.'); ?></p>
				<?php endif; ?>
			<?php else: ?>
				<p><?php echo '<b>' . $this->__('NOTE: ') . '</b>' . $this->__('Item has not been shipped yet. You can give feedback after invoice generation.'); ?></p>
			<?php endif; ?>
		</div>		
    </td>
</tr>
